In [11]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [4]:
mtcars = pd.read_csv('mtcars.csv')

In [18]:
mtcars.head(5)

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [9]:
X = mtcars[['wt','hp']]
Y = mtcars ['mpg']

In [20]:
linear = LinearRegression(fit_intercept=True) # instantatiate the linear regression model
linear.fit(X, Y)
rsq_score = linear.score(X,Y)

print("R Square is", np.round(rsq_score, 3))
print("Coefficients are",np.round(linear.coef_, 3))
print("Intercept is",np.round(linear.intercept_,3))

R Square is 0.827
Coefficients are [-3.878 -0.032]
Intercept is 37.227